version: '3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teatr
    networks: 
      - customnetwork
    ports:
      - 5432:5432

  cacher:
    container_name: cacher
    command: ["redis-server", "/etc/redis/redis.conf"]
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - postgres
    networks: 
      - customnetwork
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks: 
      - customnetwork

  expressjs:
    build: 
      context: ./expressjs
      dockerfile: Dockerfile.dev
    container_name: expressjs
    depends_on:
      - postgres
    volumes:
      - ./expressjs:/usr/src/app
    ports:
      - 8001:8001
    networks: 
      - customnetwork

  frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile.dev
      container_name: frontend
      volumes:
        - ./frontend:/usr/src/app
      ports:
        - 5173:5173
      networks: 
        - customnetwork

  reverse-proxy:
    image: nginx:1.20.0
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - expressjs
      - frontend
    ports:
        - '80:80'
    links:
        - expressjs
        - postgres
        - adminer
    networks:
        - customnetwork
    volumes:
        - './expressjs/storage:/var/www/storage'
        - './nginx:/var/log/nginx'
        - './nginx/dev/conf.d:/etc/nginx/conf.d'



networks:
  customnetwork:
    external: False
