version: '3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teatr
    networks: 
      - customnetwork
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks: 
      - customnetwork


  fastapi:
    build: 
      context: ./fastapi
      dockerfile: Dockerfile.dev
    container_name: fastapi
    depends_on:
      - postgres
    volumes:
      - ./fastapi:/usr/src/app
    ports:
      - 8000:8000
    
    networks: 
      - customnetwork

  nextjs:
      build: 
        context: ./nextjs
        dockerfile: Dockerfile
      container_name: nextjs
      volumes:
        - ./nextjs:/usr/src/app
      ports:
        - 3000:3000
      networks: 
        - customnetwork

  reverse-proxy:
    image: nginx:1.20.0
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - fastapi
    ports:
        - '80:80'
    links:
        - fastapi
        - postgres
        - adminer
    networks:
        - customnetwork
    volumes:
        - './fastapi/storage:/var/www/back-storage'
        - './nextjs/storage:/var/www/front-storage'
        - './nginx:/var/log/nginx'
        - './nginx/conf.d:/etc/nginx/conf.d'



networks:
  customnetwork:
    external: False
