version: '3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teatr
    networks: 
      - customnetwork
    ports:
      - 5432:5432

  cacher:
    container_name: cacher
    command: ["redis-server", "/etc/redis/redis.conf"]
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - postgres
    networks: 
      - customnetwork
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf

  pgadmin: 
    container_name: pgadmin
    image: dpage/pgadmin4:6.13
    restart: always
    ports:
      - 9000:80
    depends_on:
      - postgres
    networks: 
      - customnetwork
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ru
      - PGADMIN_DEFAULT_PASSWORD=123456

  expressjs:
    build: 
      context: ./expressjs
      dockerfile: Dockerfile
    container_name: expressjs
    depends_on:
      - postgres
    volumes:
      - ./expressjs:/usr/src/app
    ports:
      - 8001:8001
    networks: 
      - customnetwork

  reverse-proxy:
    image: nginx:1.20.0
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - expressjs
    ports:
        - '80:80'
    links:
        - expressjs
        - postgres
        - pgadmin
    networks:
        - customnetwork
    volumes:
        - './expressjs/storage:/var/www/storage'
        - './frontend/dist:/var/www/reservations'
        - './nginx:/var/log/nginx'
        - './nginx/prod/conf.d:/etc/nginx/conf.d'



networks:
  customnetwork:
    external: False
