"""initial

Revision ID: 40a9e8b94094
Revises: 
Create Date: 2022-02-03 08:06:36.206802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a9e8b94094'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoriums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoriums_id'), 'auditoriums', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_id'), 'plays', ['id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('firstname', sa.String(length=70), nullable=True),
    sa.Column('middlename', sa.String(length=70), nullable=True),
    sa.Column('lastname', sa.String(length=70), nullable=True),
    sa.Column('reservation_counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('plays_to_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_play', sa.Integer(), nullable=False),
    sa.Column('id_image', sa.Integer(), nullable=False),
    sa.Column('is_poster', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_image'], ['images.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_play'], ['plays.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_to_images_id'), 'plays_to_images', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_row', sa.Integer(), nullable=False),
    sa.Column('number_seat', sa.Integer(), nullable=False),
    sa.Column('id_auditorium', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_auditorium'], ['auditoriums.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_play', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_play'], ['plays.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('site_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expiration_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_sessions_id'), 'site_sessions', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_record', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_record'], ['records.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_session'], ['sessions.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('seats_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_seat'], ['seats.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_session'], ['sessions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_prices_id'), 'seats_prices', ['id'], unique=False)
    op.create_table('reservations_to_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reservation', sa.Integer(), nullable=False),
    sa.Column('id_seat_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_seat_price'], ['seats.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_to_seats_id'), 'reservations_to_seats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_to_seats_id'), table_name='reservations_to_seats')
    op.drop_table('reservations_to_seats')
    op.drop_index(op.f('ix_seats_prices_id'), table_name='seats_prices')
    op.drop_table('seats_prices')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_site_sessions_id'), table_name='site_sessions')
    op.drop_table('site_sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_plays_to_images_id'), table_name='plays_to_images')
    op.drop_table('plays_to_images')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_plays_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_auditoriums_id'), table_name='auditoriums')
    op.drop_table('auditoriums')
    # ### end Alembic commands ###
