"""initial

Revision ID: ad2a1631b021
Revises: 
Create Date: 2022-01-27 09:37:25.337297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2a1631b021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoriums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoriums_id'), 'auditoriums', ['id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_id'), 'plays', ['id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('firstname', sa.String(length=70), nullable=True),
    sa.Column('middlename', sa.String(length=70), nullable=True),
    sa.Column('lastname', sa.String(length=70), nullable=True),
    sa.Column('reservation_counter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_row', sa.Integer(), nullable=False),
    sa.Column('number_seat', sa.Integer(), nullable=False),
    sa.Column('id_auditorium', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_auditorium'], ['auditoriums.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_play', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_play'], ['plays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_session', sa.Integer(), nullable=True),
    sa.Column('id_record', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_record'], ['records.id'], ),
    sa.ForeignKeyConstraint(['id_session'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('reservations_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reservation', sa.Integer(), nullable=False),
    sa.Column('id_seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_seat'], ['seats.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_seats_id'), 'reservations_seats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_seats_id'), table_name='reservations_seats')
    op.drop_table('reservations_seats')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_plays_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_index(op.f('ix_auditoriums_id'), table_name='auditoriums')
    op.drop_table('auditoriums')
    # ### end Alembic commands ###
