"""initial

Revision ID: d4c190a5d275
Revises: 
Create Date: 2022-02-23 21:27:41.120637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4c190a5d275'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoriums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_user_reservations', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoriums_id'), 'auditoriums', ['id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_id'), 'plays', ['id'], unique=False)
    op.create_table('price_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_policy_id'), 'price_policy', ['id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=70), nullable=False),
    sa.Column('firstname', sa.String(length=70), nullable=True),
    sa.Column('middlename', sa.String(length=70), nullable=True),
    sa.Column('lastname', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.create_table('auditorium_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id_auditorium', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_auditorium'], ['auditoriums.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorium_rows_id'), 'auditorium_rows', ['id'], unique=False)
    op.create_table('plays_to_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_play', sa.Integer(), nullable=False),
    sa.Column('id_image', sa.Integer(), nullable=False),
    sa.Column('is_poster', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_image'], ['images.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_play'], ['plays.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plays_to_images_id'), 'plays_to_images', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('id_play', sa.Integer(), nullable=False),
    sa.Column('id_price_policy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_play'], ['plays.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_price_policy'], ['price_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('auditorium_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id_row', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_row'], ['auditorium_rows.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorium_seats_id'), 'auditorium_seats', ['id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_code', sa.String(length=6), nullable=False),
    sa.Column('id_session', sa.Integer(), nullable=False),
    sa.Column('id_record', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_record'], ['records.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_session'], ['sessions.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_id'), 'reservations', ['id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id_price_policy', sa.Integer(), nullable=False),
    sa.Column('id_seat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_price_policy'], ['price_policy.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_seat'], ['auditorium_seats.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    op.create_table('reservations_to_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reservation', sa.Integer(), nullable=False),
    sa.Column('id_slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_reservation'], ['reservations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_slot'], ['slots.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_to_slots_id'), 'reservations_to_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_to_slots_id'), table_name='reservations_to_slots')
    op.drop_table('reservations_to_slots')
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_reservations_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_auditorium_seats_id'), table_name='auditorium_seats')
    op.drop_table('auditorium_seats')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_plays_to_images_id'), table_name='plays_to_images')
    op.drop_table('plays_to_images')
    op.drop_index(op.f('ix_auditorium_rows_id'), table_name='auditorium_rows')
    op.drop_table('auditorium_rows')
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_price_policy_id'), table_name='price_policy')
    op.drop_table('price_policy')
    op.drop_index(op.f('ix_plays_id'), table_name='plays')
    op.drop_table('plays')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_auditoriums_id'), table_name='auditoriums')
    op.drop_table('auditoriums')
    # ### end Alembic commands ###
