// Play Reducer
export const FETCH_PLAY = 'FETCH_PLAY'
export const FETCH_PLAYS = 'FETCH_PLAYS'

// Session Reducer
export const FETCH_SESSION = 'FETCH_SESSION'
export const FETCH_SESSIONS = 'FETCH_SESSIONS'
export const FETCH_FILTERED_SESSIONS = 'FETCH_FILTERED_SESSIONS'
export const FETCH_SESSION_FILTER_OPTIONS = 'FETCH_SESSION_FILTER_OPTIONS'
export const FETCH_SESSIONS_BY_PLAY = 'FETCH_SESSIONS_BY_PLAY'
export const FETCH_SLOTS = 'FETCH_SLOTS'

// Reservation Reducer
export const POST_RESERVATION = 'POST_RESERVATION'
export const ERROR_RESERVATION = 'ERROR_RESERVATION'
export const SET_RESERVATION = 'SET_RESERVATION'
export const FETCH_RESERVATION = 'FETCH_RESERVATION'
export const SHOW_CONFIRMATION_FIELD = 'SHOW_CONFIRMATION_FIELD'
export const HIDE_CONFIRMATION_FIELD = 'HIDE_CONFIRMATION_FIELD'
export const ADD_SLOT = 'ADD_SLOT'
export const DELETE_SLOT = 'DELETE_SLOT'
