logging:
  level:
    org.hibernate.SQL: DEBUG
server:
  port: 8081
spring:
  debug: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/teatr"
    username: "user"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: "update"