// Play Reducer
export const FETCH_PLAY = 'FETCH_PLAY'
export const FETCH_PLAYS = 'FETCH_PLAYS'
export const ERROR_PLAY = 'ERROR_PLAY'
export const SUCCESS_PLAY = 'SUCCESS_PLAY'
export const CLEAR_SUCCESS_ERROR_PLAY = "CLEAR_SUCCESS_ERROR_PLAY"

// Session Reducer
export const FETCH_SESSION = 'FETCH_SESSION'
export const FETCH_SESSIONS = 'FETCH_SESSIONS'
export const FETCH_FILTERED_SESSIONS = 'FETCH_FILTERED_SESSIONS'
export const FETCH_SESSION_FILTER_OPTIONS = 'FETCH_SESSION_FILTER_OPTIONS'
export const FETCH_SESSIONS_BY_PLAY = 'FETCH_SESSIONS_BY_PLAY'
export const FETCH_SLOTS = 'FETCH_SLOTS'
export const CREATE_SESSIONS_CSV = 'CREATE_SESSIONS_CSV'
export const SUCCESS_SESSION = 'SUCCESS_SESSION'
export const ERROR_SESSION = 'ERROR_SESSION'
export const CLEAR_SUCCESS_ERROR_SESSION = "CLEAR_SUCCESS_ERROR_SESSION"

// Reservation Reducer
export const ERROR_RESERVATION_SET_DEFAULT = 'ERROR_RESERVATION_SET_DEFAULT'
export const ERROR_RESERVATION = 'ERROR_RESERVATION'
export const ERROR_CONFIRMATION = 'ERROR_CONFIRMATION'
export const POST_RESERVATION = 'POST_RESERVATION'
export const POST_CONFIRMATION = 'POST_CONFIRMATION'
export const SET_RESERVATION = 'SET_RESERVATION'
export const DELETE_RESERVATION = "DELETE_RESERVATION"
export const PAYMENT_RESERVATION = "PAYMENT_RESERVATION"
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS'
export const FETCH_RESERVATION = 'FETCH_RESERVATION'
export const ADD_SLOT = 'ADD_SLOT'
export const DELETE_SLOT = 'DELETE_SLOT'
export const CLEAR_SLOTS = 'CLEAR_SLOTS'
export const FETCH_RESERVATION_FILTER_OPTIONS = 'FETCH_RESERVATION_FILTER_OPTIONS'
export const FETCH_FILTERED_RESERVATIONS = 'FETCH_FILTERED_RESERVATIONS'


// User Reducer
export const REGISTER = 'REGISTER'
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const FETCH_PERSONAL_AREA = 'FETCH_PERSONAL_AREA'
export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PERSONAL_INFO = "CHANGE_PERSONAL_INFO"
export const SUCCESS_USER_SET_DEFAULT = "SUCCESS_USER_SET_DEFAULT" 
export const ERROR_USER = 'ERROR_USER'
export const ERROR_USER_SET_DEFAULT = 'ERROR_USER_SET_DEFAULT'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const CREATE_USERS_CSV = 'CREATE_USERS_CSV' 

// Design Reducer
export const TOGGLE_NAVBAR = "TOGGLE_NAVBAR"
export const SET_IS_LOADING = "SET_IS_LOADING"
